### ISSUE TITLE
第一时间来膜上海人

### ISSUE THREAD

**Issue by ZeroWeight** [mcfloundinho/intro-programming-homework#1]
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)
![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)![](https://imgsa.baidu.com/forum/w%3D580/sign=00c6e485a8014c08193b28ad3a7a025b/290e3badcbef7609a2d4f0b32fdda3cc7dd99e3d.jpg)

**Comment by ZeroWeight** [comment]
开源了这么多****大一****的作业，我似乎明白了什么

**Comment by yiwenlu66** [comment]
1. 您真无聊 →_→
2. 您脑洞真大 →_→
